# Generated by Django 3.1.6 on 2021-04-13 16:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('posts', '0007_auto_20210413_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('bio', models.CharField(default='', max_length=200)),
                ('profilePic', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.RenameField(
            model_name='post',
            old_name='poster',
            new_name='userPosted',
        ),
    ]
